{
 "title": "Combined Application Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UC3 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "incoming_messages_total{instance=\"api-service:8000\", job=\"api_service\", subservice=\"DENM\"}"
    }
   ]
  },
  {
   "title": "Messages Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "incoming_messages_created{instance=\"api-service:8000\", job=\"api_service\", subservice=\"DENM\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "up{instance=\"api-service:8000\", job=\"api_service\"}"
    }
   ]
  },
  {
   "title": "UC1 Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\"com_hivemq_app.+_connection_time\"}"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\"com_hivemq_app.+_connection_count\"}"
    }
   ]
  },
  {
   "title": "Published Public Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{__name__=~\"com_hivemq_app.+_messages_publish_public_count\"}"
    }
   ]
  },
  {
   "title": "Received Public Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "{__name__=~\"com_hivemq_app.+_messages_receive_public_count\"}"
    }
   ]
  }
 ]
}