{
 "title": "Application Metrics",
 "tags": [ "vodafone" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Times",
   "type": "timeseries",
   "description": "connection times of all clients in seconds (calculated on disconnect)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"com_hivemq_vodafone_app.+_connection_time\"}"
    }
   ]
  },
  {
   "title": "Number of Connections",
   "type": "timeseries",
   "description": "Total number of connections ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"com_hivemq_vodafone_app.+_connection_count\"} "
    }
   ]
  },
  {
   "title": "Published Public Message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"com_hivemq_vodafone_app.+_messages_publish_public_count\"}"
    }
   ]
  },
  {
   "title": "Received Public Message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"com_hivemq_vodafone_app.+_messages_receive_public_count\"}"
    }
   ]
  }
 ]
}