FROM ubuntu:latest

# switch mirrors to HTTPS, then update/install
RUN sed -i 's|http://|https://|g' /etc/apt/sources.list /etc/apt/sources.list.d/*.list 2>/dev/null || true \
 && apt-get -o Acquire::Retries=5 update \
 && apt-get install -y curl jq

COPY ./nifi/nifi-init.sh /opt/scripts/nifi-init.sh
RUN chmod +x /opt/scripts/nifi-init.sh

CMD ["/opt/scripts/nifi-init.sh"]
