FROM apache/nifi:1.19.0

USER root

# Install Python and pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Install required Python libraries
RUN pip3 install xmltodict asn1tools

USER nifi
